---
- name: Installer paquets nécessaires
  apt:
    name:
      - htop
      - fail2ban
      - ufw
    state: present
    update_cache: true

- name: Désactiver login root SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Désactiver PasswordAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Redémarrer SSH
  service:
    name: ssh
    state: restarted

- name: Activer fail2ban
  service:
    name: fail2ban
    state: started
    enabled: true