---
- name: "Installer FW"
  apt:
    name: ufw
    state: present
  become: yes

- name: "Autoriser SSH"
  ufw:
    rule: allow
    port: 22

- name: "Autoriser HTTP"
  ufw:
    rule: allow
    port: 80

- name: "Autoriser HTTPS"
  ufw:
    rule: allow
    port: 443

- name: "Activer FW"
  ufw:
    state: enabled
  become: yes